global:
  thresh: 0.3
  box_thresh: 0.5
  max_candidates: 1000
  unclip_ratio: 1.5
det:
  algorithm: DB
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  k: 50
  epoch: 1200
  log_smooth_window: 20
train:
  image_shape: [3, 640, 640]
  img_dir: ./data/icdar2015/
  label_path:  ./data/icdar2015/train_icdar2015_label.txt
  batch_size: 8
  init_weight_path: ./checkpoints/2020-10-22/db_15_2.3313_4.3808.h5
  save_weight_path: ./ckpts
test:
  image_shape: [3, 736, 1280]
  img_dir: ./data/icdar2015/
  label_path:  ./data/icdar2015/test_icdar2015_label.txt
  batch_size: 8
  init_weight_path: