rec:
  algorithm: CRNN
  main_loss_type: CTC
  use_space_char: false
  epoch: 1200
  max_text_length: 25
  character_type: ch
  character_dict_path: ./ppocr/utils/ppocr_keys_v1.txt
  log_smooth_window: 20
train:
  image_shape: [3, 640, 640]
  greedy: True,
  beam_width: 100,
  top_paths: 1,
  img_dir: E:/dm/samples/icdar2015/
  label_path:  E:/dm/samples/icdar2015/train_icdar2015_label.txt
  batch_size: 4
  init_weight_path:
  save_weight_path: ./ckpts
test:
  image_shape: [3, 640, 640]
  img_dir: E:/dm/samples/icdar2015/
  label_path:  E:/dm/samples/icdar2015/test_icdar2015_label.txt
  batch_size: 2
  init_weight_path: