global:
  epochs: 30
  max_text_length: 25
  character_type: en
  use_space_char: true
  loss_type: ctc
  hidden_size: 96
  character_dict_path: ./data/ic15_data/ic15_dict.txt
train:
  image_shape: [32, 320, 3]
  distort: true
  greedy: true
  beam_width: 100
  top_paths: 1
  img_dir: ./data/ic15_data
  label_path:  ./data/ic15_data/rec_gt_train.txt
  batch_size: 16
  init_weight_path: ./checkpoints/2020-10-30/db_30_9.7126_10.2521.h5
  save_weight_path: ./ckpts
test:
  image_shape: [32, 320, 3]
  distort: false
  img_dir: ./data/ic15_data
  label_path:  ./data/ic15_data/rec_gt_test.txt
  batch_size: 4
  init_weight_path: