train:
  image_shape: [3, 32, 100]
  max_text_length: 25
  character_type: en
  use_space_char: True
  epoch: 1200
  character_dict_path: ./data/ic15_data/ic15_dict.txt
  loss_type: ctc
  distort: True,
  greedy: True,
  beam_width: 100,
  top_paths: 1,
  img_dir: E:/dm/samples/ic15_data/
  label_path:  E:/dm/samples/ic15_data/rec_gt_train.txt
  batch_size: 4
  init_weight_path:
  save_weight_path: ./ckpts
test:
  image_shape: [ 3, 32, 100 ]
  max_text_length: 25
  character_type: en
  use_space_char: True
  epoch: 1200
  character_dict_path: ./data/ic15_data/ic15_dict.txt
  loss_type: ctc
  distort: False,
  img_dir: E:/dm/samples/ic15_data/
  label_path:  E:/dm/samples/ic15_data/rec_gt_test.txt
  batch_size: 2
  init_weight_path: