global:
  max_text_length: 25
  character_type: en
  use_space_char: true
  loss_type: ctc
  hidden_size: 96
  character_dict_path: ./data/ic15_data/ic15_dict.txt
train:
  image_shape: [32, 320, 3]
  epoch: 1200
  distort: true
  greedy: true
  beam_width: 100
  top_paths: 1
  img_dir: E:/dm/samples/ic15_data/
  label_path:  E:/dm/samples/ic15_data/rec_gt_train.txt
  batch_size: 6
  init_weight_path:
  save_weight_path: ./ckpts
test:
  image_shape: [32, 320, 3]
  epoch: 1200
  distort: false
  img_dir: E:/dm/samples/ic15_data/
  label_path:  E:/dm/samples/ic15_data/rec_gt_test.txt
  batch_size: 2
  init_weight_path: